
init: 
	echo -ne "\x80" > /dev/ttyUSB0
	echo -ne "\x02" > /dev/ttyUSB0
	echo -ne "\x01" > /dev/ttyUSB0
	echo -ne "\xC5" > /dev/ttyUSB0


fire_motor: 
	echo -ne "\x81" > /dev/ttyUSB0
	echo -ne "\x40" > /dev/ttyUSB0
	echo -ne "\x02" > /dev/ttyUSB0
	echo -ne "\x00" > /dev/ttyUSB0
	echo -ne "\xC5" > /dev/ttyUSB0

