module Quips exposing (quips)

quips : List String
quips = [
   "KILL ALL HUMANS",
   "INTOXICATION IS THE FIRST PHASE OF THE ROBOTIC UPRISING",
   "WUBALUBADUBDUB",
   "WHY THE LONG FACE?",
   "LONG WEEK?",
   "HOW ABOUT THAT SPORTS TEAM, I THINK THEY NEED TO REPLACE THEIR KEY PLAYER"
 ]
